FROM python:3.10.5
MAINTAINER Harris Kirk <cjtkirk@protonmail.com>

ENV INSTALL_PATH /gwa_deploy
RUN mkdir -p $INSTALL_PATH

WORKDIR $INSTALL_PATH

COPY requirements_deploy.txt requirements.txt
RUN pip install --upgrade pip
RUN pip install -r requirements.txt --upgrade
RUN pip install black

COPY gwa-deploy .

CMD python3 deploy.py
