FROM python:3.10.5
MAINTAINER Harris Kirk <cjtkirk@protonmail.com>

ENV INSTALL_PATH /gwa_deploy
RUN mkdir -p $INSTALL_PATH

WORKDIR $INSTALL_PATH

COPY requirements_deploy.txt requirements.txt
RUN pip install --upgrade pip
RUN pip install -r requirements.txt --upgrade
RUN pip install black

# Download kubectl for working with the k8s cluster
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" ;\
    mv kubectl /bin ;\
    chmod 775 /bin/kubectl

COPY gwa-deploy .

