#!/usr/bin/env python
"""
Manage all aspects of the creation of infrastructure and app deployment
"""
from common import execute_linode_cli, execute_sh
import switch as switch_module
import linodeapi
import subprocess
import kubectl
import logging
import time
import base64
import json
import sys
import os
from retry import retry
import requests
import typer

PROJECT_ACRONYM = 'bgd'

app = typer.Typer()


KUBERNETES_VERSION = "1.27"

def set_logging_level(level_param : str):

    # Remove any existing handlers
    for handler in logging.root.handlers[:]:
        logging.root.removeHandler(handler)

    level_param = level_param.lower()  # Convert to lowercase for case-insensitivity

    match level_param:
        case "debug":
            logging_level = logging.DEBUG
        case "info":
            logging_level = logging.INFO
        case "warning":
            logging_level = logging.WARNING
        case "error":
            logging_level = logging.ERROR
        case "critical":
            logging_level = logging.CRITICAL
        case _:
            raise ValueError(f"Invalid log level: {level_param}")

    logging.basicConfig(
        format="%(asctime)s %(levelname)-9s %(funcName)-30s() %(message)s ",
        level=logging_level,
        datefmt="%Y-%m-%d at %H:%M:%S",
    )

set_logging_level("debug")

@retry(tries=60, delay=60)
def get_kubeconfig(cluster_id):
    cmd = [
        "linode-cli",
        "lke",
        "kubeconfig-view",
        cluster_id,
    ]
    json_object = execute_linode_cli(cmd)
    base_64_kubeconfig = json_object[0]["kubeconfig"]
    logging.debug(f"kubeconfig base64: {base_64_kubeconfig}")
    logging.info(f"kubeconfig received OK from cluster {cluster_id}")
    return base64.b64decode(base_64_kubeconfig).decode("ascii")


def create_cluster(env):
    """Create a Akamai K8S cluster"""
    cmd = [
        "linode-cli",
        "lke",
        "cluster-create",
        "--tags",
        f"env_{env}",
        "--tags",
        f"project_{PROJECT_ACRONYM}", 
        "--label",
        f"{PROJECT_ACRONYM} cluster for {env}",
        "--region",
        "us-east",
        "--node_pools.type",
        "g6-standard-1",
        "--k8s_version",
        KUBERNETES_VERSION,
        "--node_pools.count",
        kubectl.KUBERNETES_NODE_COUNT,
    ]
    json_object = execute_linode_cli(cmd)
    cluster_id = json_object[0]["id"]
    return str(cluster_id)

def delete_nodebalancer(nodebalancer_id):
    """Delete nodebalancer"""
    cmd = [
        "linode-cli",
        "nodebalancers",
        "delete",
        nodebalancer_id,
    ]
    json_object = execute_linode_cli(cmd)
    logging.debug(f"nodebalancer delete returned {json_object}")
    logging.info(f"nodebalancer id '{nodebalancer_id}' was deleted")
    return

def set_nodebalancer_tags(env, nodebalancer_id):
    """Set tags on the k8s service's nodebalancer"""
    cmd = [
        "linode-cli",
        "nodebalancers",
        "update",
        nodebalancer_id,
        "--tags",
        f"project_{PROJECT_ACRONYM}", 
        "--tags",
        f"env_{env}",
    ]
    execute_linode_cli(cmd)
    return

def delete_cluster(cluster_id):
    kubectl.delete_service()  # Must delete the NodeBalancer before and in addition to the cluster
    delete_cluster_only(cluster_id)
    return


def delete_cluster_only(cluster_id):
    cmd = ["linode-cli", "lke", "cluster-delete", cluster_id]
    json_object = execute_linode_cli(cmd)
    logging.debug(f"cluster-delete returned {json_object}")
    logging.info(f"Cluster id '{cluster_id}' was deleted")
    return


def write_kubeconfig(kubeconfig):
    KUBECONFIG_DIR = os.environ["HOME"] + "/.kube"
    KUBECONFIG_FILE_PATH = KUBECONFIG_DIR + "/config"
    try:
        os.mkdir(KUBECONFIG_DIR)
    except FileExistsError:
        pass
    with open(KUBECONFIG_FILE_PATH, "w") as file:
        file.write(kubeconfig)
    logging.info(f"kubernetes config file written: {KUBECONFIG_FILE_PATH}")
    return


def deployment_smoke_test(ingress_ip):
    response_text = wait_for_http_get(ingress_ip)
    logging.debug(f"Response: {response_text}")
    if "Richmond" not in response_text:
        return False
    logging.info("[OK] Site smoke test passes")
    return True


@retry(tries=120, delay=30)
def wait_for_http_get(ingress_ip):
    smoke_test_url = f"http://{ingress_ip}:8000"
    logging.debug(f"Invoking {smoke_test_url} ...")
    response = requests.get(smoke_test_url)
    logging.debug(f"response_code was: {response.status_code}")
    if response.status_code == 200:
        return response.text
    else:
        raise Exception(f"ERROR: smoke test status code was {response.status_code}.")

def install_argocd():
    cmd = ["helm", "template"]
    logging.debug(f"{cmd}")    
    completed_process = subprocess.run(cmd, cwd="./resources", check=True, shell=True, capture_output=True)
    with open('./resources/argocd.yaml', "w") as file:
        file.write(completed_process.stdout.decode())
    kubectl.apply_argocd()
    logging.info("argocd manifest applied OK")
    return
    

def deploy_kubernetes_artifacts(env):
    cluster_id = create_cluster(env)
    logging.info(f"Cluster id '{cluster_id}' was created")
    logging.info(f"Waiting to receive kubeconfig...")
    try:
        kubeconfig = get_kubeconfig(cluster_id)
    except Exception as e:
        logging.error(f"Waiting period for linode to provide the kubeconfig has expired.  Deleting cluster '{cluster_id}' and aborting.")
        logging.exception("An exception occurred: %s", str(e))
        delete_cluster(cluster_id)  # delete cluster to not incur charges
        sys.exit(2) # 2 is linode timeout
    logging.debug(f"kubeconfig as yaml: {kubeconfig}")
    write_kubeconfig(kubeconfig)
    kubectl.get_nodes()
    install_argocd()
    kubectl.create_secrets()
    kubectl.apply_deployment()
    kubectl.apply_service()
    ingress_ip = kubectl.get_ingress_ip()
    return cluster_id, ingress_ip

def delete_environment(env: str):
    """Delete Akamai items associated with this project and env"""
    cluster_id = linodeapi.get_cluster_id(PROJECT_ACRONYM, env)
    if cluster_id:
        logging.info(f"Cluster ID in environment {env} found: {cluster_id}")
        delete_cluster_only(cluster_id)

    nodebalancer_id = linodeapi.get_nodebalancer_id(PROJECT_ACRONYM, env)
    if nodebalancer_id:
        logging.info(f"nodebalancer ID in environment {env} found: {nodebalancer_id}") 
        delete_nodebalancer(nodebalancer_id)

    switch_resp = switch_module.switch_get(env)
    if switch_resp != []:
        switch_id = switch_resp[0]["id"]
        logging.warning(f"switch ID in environment {env} found (no action taked): {switch_id}") 

#\
# All cli commands follow:
#/
@app.command()
def deploy(env: str, keep: bool = typer.Option(False, help="Keep the cluster running after deployment and test"), keep_switch: bool = typer.Option(False, help="Keep the switch running after deployment and test"), log_level = "debug"
):
    set_logging_level(log_level)

    """Deploy a kubernetes cluster in the requested environment"""
    delete_environment(env) # Ensure there is no existing environment
    logging.info(f"Creating k8s environment '{env}' with keep={keep}")
    cluster_id, ingress_ip = deploy_kubernetes_artifacts(env)
    tests_pass = deployment_smoke_test(ingress_ip)

    switch_module.switch_delete(env)
    switch_module.switch_create(env)

    switch_ip = switch_module.switch_view(env)
    if not switch_ip == '':
        switch_module.switch_smoke_test(switch_ip)
    else:
        raise Exception("ERROR: failed to retrieve switch IP")

    logging.debug(f"Attempt to set switch target IP to cluster's ingress IP ({ingress_ip})")
    switch_module.switch_ip_set(env, ingress_ip)
    switch_proxy_tests_pass = deployment_smoke_test(switch_ip)

    k8s_nodes = linodeapi.get_k8s_nodes()
    logging.info(f"Number of lke linodes: {len(k8s_nodes)}")
    nodebalancer_id = linodeapi.get_nodebalancer_id_by_ingress(ingress_ip)
    logging.info(f"The nodebalancer id of the service is: {nodebalancer_id}")
    set_nodebalancer_tags(env, nodebalancer_id)
    logging.info(f"Querying for cluster ID with tag env_{env} and found: {linodeapi.get_cluster_id(PROJECT_ACRONYM, env)}")
    if not keep:
        delete_cluster(cluster_id)  # delete cluster to not incur charges
    else:
        logging.info(f"Cluster ID {cluster_id} is running and incurring charges!")

    if not keep_switch:
        switch_module.switch_delete(env)
    else:
        logging.info(f"Switch is running and incurring charges!")

    if not tests_pass:
        raise Exception("ERROR: Tests of index.html page failed")

    if not switch_proxy_tests_pass:
        raise Exception("ERROR: Tests of index.html page failed (via switch proxy)")

    return

@app.command()
def ls(
    env: str , log_level = "debug"
):
    set_logging_level(log_level)

    """List Akamai items associated with this project and env"""
    cluster_id = linodeapi.get_cluster_id(PROJECT_ACRONYM, env)
    logging.info(f"Cluster ID with tag 'env_{env}': {cluster_id}")  
    nodebalancer_id = linodeapi.get_nodebalancer_id(PROJECT_ACRONYM, env)
    logging.info(f"nodebalancer ID with tag 'env_{env}': {nodebalancer_id}")
    switch_id = switch_module.switch_view(env)
    logging.info(f"switch id with tag 'env_{env}: {switch_id}")

@app.command()
def rm(
    env: str , log_level = "debug"
):
    set_logging_level(log_level)

    """Remove all artifacts in the env"""
    delete_environment(env)

@app.command()
def switch(operation: str, env: str, log_level = "debug"):
    set_logging_level(log_level)

    """Perform all operations related to the front-end nginx switch"""
    match operation:
        case "create": 
            switch_module.switch_create(env)
        case "view": switch_module.switch_view(env)
        case "delete": switch_module.switch_delete(env)
        case _:
            raise Exception("invalid switch command")

@app.command()
def switch_set_ip_target_to_cluster(env: str, target_env: str):
    switch_module.switch_set_ip_target_to_cluster(env, target_env)

    logging.info(f"nginx switch (env: {env}) succesfully set to target ({target_env})")


if __name__ == "__main__":
    app()
