#!/usr/bin/env python
"""
Manage all aspects of the creation of infrastructure and app deployment
"""
from common import execute_linode_cli, execute_sh
import linodeapi
import subprocess
import kubectl
import logging
import time
import base64
import json
import sys
import os
from retry import retry
import requests
import typer

PROJECT_ACRONYM = 'bgd'

app = typer.Typer()

logging.basicConfig(
    format="%(asctime)s %(levelname)-9s %(funcName)-30s() %(message)s ",
    level=logging.INFO,
    datefmt="%Y-%m-%d at %H:%M:%S",
)

KUBERNETES_VERSION = "1.26"


@retry(tries=50, delay=30)
def get_kubeconfig(cluster_id):
    cmd = [
        "linode-cli",
        "--json",
        "lke",
        "kubeconfig-view",
        cluster_id,
    ]
    json_object = execute_linode_cli(cmd)
    base_64_kubeconfig = json_object[0]["kubeconfig"]
    logging.debug(f"kubeconfig base64: {base_64_kubeconfig}")
    logging.info(f"kubeconfig received OK from cluster {cluster_id}")
    return base64.b64decode(base_64_kubeconfig).decode("ascii")


def create_cluster(k8s_env):
    """Create a K8S cluster"""
    cmd = [
        "linode-cli",
        "lke",
        "cluster-create",
        "--tags",
        f"env_{k8s_env}",
        "--tags",
        f"project_{PROJECT_ACRONYM}", 
        "--label",
        f"{PROJECT_ACRONYM} cluster for {k8s_env}",
        "--region",
        "us-east",
        "--node_pools.type",
        "g6-standard-1",
        "--k8s_version",
        KUBERNETES_VERSION,
        "--node_pools.count",
        kubectl.KUBERNETES_NODE_COUNT,
        "--json",
    ]
    json_object = execute_linode_cli(cmd)
    cluster_id = json_object[0]["id"]
    return str(cluster_id)

def delete_nodebalancer(nodebalancer_id):
    """Delete nodebalancer"""
    cmd = [
        "linode-cli",
        "nodebalancer",
        "delete",
        nodebalancer_id,
        "--json",
    ]
    json_object = execute_linode_cli(cmd)
    logging.debug(f"nodebalancer delete returned {json_object}")
    logging.info(f"nodebalancer id '{nodebalancer_id}' was deleted")
    return

def set_nodebalancer_tags(k8s_env, nodebalancer_id):
    """Set tags on the k8s service's nodebalancer"""
    cmd = [
        "linode-cli",
        "nodebalancers",
        "update",
        nodebalancer_id,
        "--tags",
        f"project_{PROJECT_ACRONYM}", 
        "--tags",
        f"env_{k8s_env}",
        "--json",
    ]
    execute_linode_cli(cmd)
    return


def delete_cluster(cluster_id):
    kubectl.delete_service()  # Must delete the NodeBalancer before and in addition to the cluster
    cmd = ["linode-cli", "lke", "cluster-delete", cluster_id]
    json_object = execute_linode_cli(cmd)
    logging.debug(f"cluster-delete returned {json_object}")
    logging.info(f"Cluster id '{cluster_id}' was deleted")
    return


def write_kubeconfig(kubeconfig):
    KUBECONFIG_DIR = os.environ["HOME"] + "/.kube"
    KUBECONFIG_FILE_PATH = KUBECONFIG_DIR + "/config"
    try:
        os.mkdir(KUBECONFIG_DIR)
    except FileExistsError:
        pass
    with open(KUBECONFIG_FILE_PATH, "w") as file:
        file.write(kubeconfig)
    logging.info(f"kubernetes config file written: {KUBECONFIG_FILE_PATH}")
    return


def deployment_smoke_test(ingress_ip):
    response = wait_for_http_get(ingress_ip)
    logging.debug(f"Response: {response.text}")
    if "Richmond" not in response.text:
        return False
    logging.info("[OK] Site smoke test passes")
    return True


@retry(tries=20, delay=10)
def wait_for_http_get(ingress_ip):
    smoke_test_url = f"http://{ingress_ip}:8000"
    logging.debug(f"Get of {smoke_test_url}")
    return requests.get(smoke_test_url)

def install_argocd():
    cmd = ["helm", "template"]
    logging.debug(f"{cmd}")    
    completed_process = subprocess.run(cmd, cwd="./resources", check=True, shell=True, capture_output=True)
    with open('./resources/argocd.yaml', "w") as file:
        file.write(completed_process.stdout.decode())
    kubectl.apply_argocd()
    logging.info("argocd manifest applied OK")
    return
    

def verify_deployment(k8s_env):
    cluster_id = create_cluster(k8s_env)
    logging.info(f"Cluster id '{cluster_id}' was created")
    logging.info(f"Waiting to receive kubeconfig...")
    try:
        kubeconfig = get_kubeconfig(cluster_id)
    except Exception as e:
        logging.error(f"Waiting period for linode to provide the kubeconfig has expired.  Deleting cluster '{cluster_id}' and aborting.")
        logging.exception("An exception occurred: %s", str(e))
        delete_cluster(cluster_id)  # delete cluster to not incur charges
        sys.exit(2) # 2 is linode timeout
    logging.debug(f"kubeconfig as yaml: {kubeconfig}")
    write_kubeconfig(kubeconfig)
    kubectl.get_nodes()
    install_argocd()
    kubectl.create_secrets()
    kubectl.apply_deployment()
    kubectl.apply_service()
    ingress_ip = kubectl.get_ingress_ip()
    return cluster_id, ingress_ip

def delete_environment(env: str):
    cluster_id = linodeapi.get_cluster_id(PROJECT_ACRONYM, env)
    logging.info(f"Cluster ID with tag 'env_{env}': {cluster_id}")    
    if cluster_id:
        delete_cluster(cluster_id)
    nodebalancer_id = linodeapi.get_nodebalancer_id(PROJECT_ACRONYM, env)
    logging.info(f"nodebalancer ID with tag 'env_{env}': {nodebalancer_id}")    
    if nodebalancer_id:
        delete_nodebalancer(nodebalancer_id)


@app.command()
def deploy(env: str, keep: bool = typer.Option(False, help="Keep the cluster running after deployment and test")):
    clusters = linodeapi.get_all_clusters()
    logging.info(f"Current clusters ids/tags are: {clusters}")
    k8s_env = env
    logging.info(f"Creating k8s environment '{k8s_env}' with keep={keep}")
    cluster_id, ingress_ip = verify_deployment(k8s_env)
    tests_pass = deployment_smoke_test(ingress_ip)
    k8s_nodes = linodeapi.get_k8s_nodes()
    logging.info(f"Number of lke linodes: {len(k8s_nodes)}")
    nodebalancer_id = linodeapi.get_nodebalancer_id_by_ingress(ingress_ip)
    logging.info(f"The nodebalancer id of the service is: {nodebalancer_id}")
    set_nodebalancer_tags(k8s_env, nodebalancer_id)
    logging.info(f"Querying for cluster ID with tag env_{env} and found: {linodeapi.get_cluster_id(PROJECT_ACRONYM, env)}")
    if not keep:
        delete_cluster(cluster_id)  # delete cluster to not incur charges
    else:
        logging.info(f"Cluster ID {cluster_id} is running and incurring charges!")
    if not tests_pass:
        raise Exception("ERROR: Tests of index.html page failed")
    return

@app.command()
def ls(
    env: str
):
    cluster_id = linodeapi.get_cluster_id(PROJECT_ACRONYM, env)
    logging.info(f"Cluster ID with tag 'env_{env}': {cluster_id}")  
    nodebalancer_id = linodeapi.get_nodebalancer_id(PROJECT_ACRONYM, env)
    logging.info(f"nodebalancer ID with tag 'env_{env}': {nodebalancer_id}")      

@app.command()
def rm(
    env: str
):
    delete_environment(env)

if __name__ == "__main__":
    app()
