sample_json = """{
    "address": "richmond, va",
    "days": [
        {
            "cloudcover": 77.0,
            "conditions": "Partially cloudy",
            "datetime": "2023-03-22",
            "datetimeEpoch": 1679457600,
            "description": "Partly cloudy throughout the day.",
            "dew": 0.7,
            "feelslike": 11.6,
            "feelslikemax": 17.8,
            "feelslikemin": 5.7,
            "humidity": 46.2,
            "icon": "partly-cloudy-day",
            "moonphase": 0.03,
            "precip": 0.0,
            "precipcover": 0.0,
            "precipprob": 12.0,
            "preciptype": null,
            "pressure": 1027.1,
            "severerisk": 10.0,
            "snow": 0.0,
            "snowdepth": 0.0,
            "solarenergy": 14.8,
            "solarradiation": 171.8,
            "source": "comb",
            "stations": [
                "KRIC",
                "KFCI",
                "F2053",
                "1269W",
                "KW96",
                "KOFP"
            ],
            "sunrise": "07:10:30",
            "sunriseEpoch": 1679483430,
            "sunset": "19:23:22",
            "sunsetEpoch": 1679527402,
            "temp": 12.1,
            "tempmax": 17.8,
            "tempmin": 7.4,
            "uvindex": 7.0,
            "visibility": 16.1,
            "winddir": 199.7,
            "windgust": 24.1,
            "windspeed": 14.8
        },
        {
            "cloudcover": 61.3,
            "conditions": "Partially cloudy",
            "datetime": "2023-03-23",
            "datetimeEpoch": 1679544000,
            "description": "Partly cloudy throughout the day.",
            "dew": 9.7,
            "feelslike": 18.5,
            "feelslikemax": 26.7,
            "feelslikemin": 11.2,
            "humidity": 58.6,
            "icon": "partly-cloudy-day",
            "moonphase": 0.06,
            "precip": 0.0,
            "precipcover": 0.0,
            "precipprob": 8.0,
            "preciptype": null,
            "pressure": 1017.8,
            "severerisk": 10.0,
            "snow": 0.0,
            "snowdepth": 0.0,
            "solarenergy": 18.6,
            "solarradiation": 216.0,
            "source": "fcst",
            "stations": null,
            "sunrise": "07:09:00",
            "sunriseEpoch": 1679569740,
            "sunset": "19:24:17",
            "sunsetEpoch": 1679613857,
            "temp": 18.5,
            "tempmax": 26.7,
            "tempmin": 11.2,
            "uvindex": 7.0,
            "visibility": 16.3,
            "winddir": 219.8,
            "windgust": 46.4,
            "windspeed": 27.7
        },
        {
            "cloudcover": 56.4,
            "conditions": "Partially cloudy",
            "datetime": "2023-03-24",
            "datetimeEpoch": 1679630400,
            "description": "Partly cloudy throughout the day.",
            "dew": 11.5,
            "feelslike": 19.1,
            "feelslikemax": 25.0,
            "feelslikemin": 11.7,
            "humidity": 62.7,
            "icon": "partly-cloudy-day",
            "moonphase": 0.1,
            "precip": 1.2,
            "precipcover": 16.67,
            "precipprob": 45.0,
            "preciptype": [
                "rain"
            ],
            "pressure": 1012.6,
            "severerisk": 10.0,
            "snow": 0.0,
            "snowdepth": 0.0,
            "solarenergy": 11.1,
            "solarradiation": 127.8,
            "source": "fcst",
            "stations": null,
            "sunrise": "07:07:29",
            "sunriseEpoch": 1679656049,
            "sunset": "19:25:12",
            "sunsetEpoch": 1679700312,
            "temp": 19.1,
            "tempmax": 25.0,
            "tempmin": 11.7,
            "uvindex": 5.0,
            "visibility": 16.1,
            "winddir": 233.7,
            "windgust": 33.5,
            "windspeed": 20.5
        },
        {
            "cloudcover": 63.8,
            "conditions": "Rain, Partially cloudy",
            "datetime": "2023-03-25",
            "datetimeEpoch": 1679716800,
            "description": "Partly cloudy throughout the day with rain in the morning and afternoon.",
            "dew": 11.1,
            "feelslike": 15.2,
            "feelslikemax": 22.8,
            "feelslikemin": 7.0,
            "humidity": 75.1,
            "icon": "rain",
            "moonphase": 0.13,
            "precip": 1.6,
            "precipcover": 16.67,
            "precipprob": 68.0,
            "preciptype": [
                "rain"
            ],
            "pressure": 1009.4,
            "severerisk": 10.0,
            "snow": 0.0,
            "snowdepth": 0.0,
            "solarenergy": 11.0,
            "solarradiation": 127.9,
            "source": "fcst",
            "stations": null,
            "sunrise": "07:05:58",
            "sunriseEpoch": 1679742358,
            "sunset": "19:26:06",
            "sunsetEpoch": 1679786766,
            "temp": 15.7,
            "tempmax": 22.8,
            "tempmin": 9.5,
            "uvindex": 3.0,
            "visibility": 18.1,
            "winddir": 183.3,
            "windgust": 47.5,
            "windspeed": 32.8
        },
        {
            "cloudcover": 8.7,
            "conditions": "Clear",
            "datetime": "2023-03-26",
            "datetimeEpoch": 1679803200,
            "description": "Clear conditions throughout the day.",
            "dew": 4.3,
            "feelslike": 16.9,
            "feelslikemax": 22.2,
            "feelslikemin": 12.3,
            "humidity": 45.4,
            "icon": "clear-day",
            "moonphase": 0.16,
            "precip": 0.0,
            "precipcover": 0.0,
            "precipprob": 29.0,
            "preciptype": null,
            "pressure": 1016.0,
            "severerisk": 10.0,
            "snow": 0.0,
            "snowdepth": 0.0,
            "solarenergy": 23.1,
            "solarradiation": 269.9,
            "source": "fcst",
            "stations": null,
            "sunrise": "07:04:27",
            "sunriseEpoch": 1679828667,
            "sunset": "19:27:01",
            "sunsetEpoch": 1679873221,
            "temp": 16.9,
            "tempmax": 22.2,
            "tempmin": 12.3,
            "uvindex": 7.0,
            "visibility": 24.1,
            "winddir": 269.2,
            "windgust": 43.8,
            "windspeed": 29.4
        },
        {
            "cloudcover": 60.7,
            "conditions": "Rain, Partially cloudy",
            "datetime": "2023-03-27",
            "datetimeEpoch": 1679889600,
            "description": "Partly cloudy throughout the day with a chance of rain.",
            "dew": 6.5,
            "feelslike": 13.4,
            "feelslikemax": 16.9,
            "feelslikemin": 10.2,
            "humidity": 63.5,
            "icon": "rain",
            "moonphase": 0.19,
            "precip": 2.0,
            "precipcover": 20.83,
            "precipprob": 51.0,
            "preciptype": [
                "rain"
            ],
            "pressure": 1012.7,
            "severerisk": 10.0,
            "snow": 0.0,
            "snowdepth": 0.0,
            "solarenergy": 16.5,
            "solarradiation": 191.5,
            "source": "fcst",
            "stations": null,
            "sunrise": "07:02:57",
            "sunriseEpoch": 1679914977,
            "sunset": "19:27:55",
            "sunsetEpoch": 1679959675,
            "temp": 13.4,
            "tempmax": 16.9,
            "tempmin": 10.2,
            "uvindex": 5.0,
            "visibility": 23.3,
            "winddir": 179.3,
            "windgust": 30.2,
            "windspeed": 21.2
        },
        {
            "cloudcover": 39.5,
            "conditions": "Partially cloudy",
            "datetime": "2023-03-28",
            "datetimeEpoch": 1679976000,
            "description": "Partly cloudy throughout the day.",
            "dew": 5.6,
            "feelslike": 11.4,
            "feelslikemax": 16.6,
            "feelslikemin": 6.1,
            "humidity": 65.9,
            "icon": "partly-cloudy-day",
            "moonphase": 0.25,
            "precip": 0.6,
            "precipcover": 8.33,
            "precipprob": 41.0,
            "preciptype": [
                "rain"
            ],
            "pressure": 1020.8,
            "severerisk": 10.0,
            "snow": 0.0,
            "snowdepth": 0.0,
            "solarenergy": 23.1,
            "solarradiation": 267.9,
            "source": "fcst",
            "stations": null,
            "sunrise": "07:01:26",
            "sunriseEpoch": 1680001286,
            "sunset": "19:28:50",
            "sunsetEpoch": 1680046130,
            "temp": 12.1,
            "tempmax": 16.6,
            "tempmin": 8.8,
            "uvindex": 6.0,
            "visibility": 24.1,
            "winddir": 312.1,
            "windgust": 40.0,
            "windspeed": 27.0
        },
        {
            "cloudcover": 9.1,
            "conditions": "Clear",
            "datetime": "2023-03-29",
            "datetimeEpoch": 1680062400,
            "description": "Clear conditions throughout the day.",
            "dew": -2.0,
            "feelslike": 6.7,
            "feelslikemax": 14.4,
            "feelslikemin": -0.2,
            "humidity": 48.3,
            "icon": "clear-day",
            "moonphase": 0.26,
            "precip": 0.0,
            "precipcover": 0.0,
            "precipprob": 19.0,
            "preciptype": null,
            "pressure": 1026.8,
            "severerisk": 10.0,
            "snow": 0.0,
            "snowdepth": 0.0,
            "solarenergy": 24.9,
            "solarradiation": 294.0,
            "source": "fcst",
            "stations": null,
            "sunrise": "06:59:56",
            "sunriseEpoch": 1680087596,
            "sunset": "19:29:44",
            "sunsetEpoch": 1680132584,
            "temp": 9.1,
            "tempmax": 14.4,
            "tempmin": 4.3,
            "uvindex": 7.0,
            "visibility": 24.1,
            "winddir": 316.1,
            "windgust": 42.5,
            "windspeed": 28.8
        },
        {
            "cloudcover": 68.4,
            "conditions": "Partially cloudy",
            "datetime": "2023-03-30",
            "datetimeEpoch": 1680148800,
            "description": "Partly cloudy throughout the day.",
            "dew": 1.1,
            "feelslike": 10.8,
            "feelslikemax": 19.0,
            "feelslikemin": 3.2,
            "humidity": 51.2,
            "icon": "partly-cloudy-day",
            "moonphase": 0.29,
            "precip": 6.8,
            "precipcover": 8.33,
            "precipprob": 28.6,
            "preciptype": [
                "rain"
            ],
            "pressure": 1019.9,
            "severerisk": 10.0,
            "snow": 0.0,
            "snowdepth": 0.0,
            "solarenergy": 17.3,
            "solarradiation": 201.0,
            "source": "fcst",
            "stations": null,
            "sunrise": "06:58:26",
            "sunriseEpoch": 1680173906,
            "sunset": "19:30:39",
            "sunsetEpoch": 1680219039,
            "temp": 11.5,
            "tempmax": 19.0,
            "tempmin": 4.9,
            "uvindex": 8.0,
            "visibility": 21.8,
            "winddir": 205.9,
            "windgust": 71.3,
            "windspeed": 26.6
        },
        {
            "cloudcover": 66.4,
            "conditions": "Rain, Partially cloudy",
            "datetime": "2023-03-31",
            "datetimeEpoch": 1680235200,
            "description": "Partly cloudy throughout the day with a chance of rain.",
            "dew": 3.3,
            "feelslike": 12.7,
            "feelslikemax": 19.1,
            "feelslikemin": 4.8,
            "humidity": 57.1,
            "icon": "rain",
            "moonphase": 0.32,
            "precip": 1.5,
            "precipcover": 12.5,
            "precipprob": 52.4,
            "preciptype": [
                "rain"
            ],
            "pressure": 1015.0,
            "severerisk": 10.0,
            "snow": 0.0,
            "snowdepth": 0.0,
            "solarenergy": 21.3,
            "solarradiation": 249.9,
            "source": "fcst",
            "stations": null,
            "sunrise": "06:56:56",
            "sunriseEpoch": 1680260216,
            "sunset": "19:31:33",
            "sunsetEpoch": 1680305493,
            "temp": 13.2,
            "tempmax": 19.1,
            "tempmin": 7.6,
            "uvindex": 8.0,
            "visibility": 22.0,
            "winddir": 312.1,
            "windgust": 58.9,
            "windspeed": 23.8
        },
        {
            "cloudcover": 68.1,
            "conditions": "Partially cloudy",
            "datetime": "2023-04-01",
            "datetimeEpoch": 1680321600,
            "description": "Partly cloudy throughout the day.",
            "dew": -6.1,
            "feelslike": 8.7,
            "feelslikemax": 16.5,
            "feelslikemin": 1.1,
            "humidity": 32.8,
            "icon": "partly-cloudy-day",
            "moonphase": 0.35,
            "precip": 0.0,
            "precipcover": 0.0,
            "precipprob": 28.6,
            "preciptype": null,
            "pressure": 1024.2,
            "severerisk": 10.0,
            "snow": 0.0,
            "snowdepth": 0.0,
            "solarenergy": 22.6,
            "solarradiation": 257.6,
            "source": "fcst",
            "stations": null,
            "sunrise": "06:55:26",
            "sunriseEpoch": 1680346526,
            "sunset": "19:32:27",
            "sunsetEpoch": 1680391947,
            "temp": 10.1,
            "tempmax": 16.5,
            "tempmin": 4.2,
            "uvindex": 8.0,
            "visibility": 24.1,
            "winddir": 26.3,
            "windgust": 45.4,
            "windspeed": 16.9
        },
        {
            "cloudcover": 100.0,
            "conditions": "Overcast",
            "datetime": "2023-04-02",
            "datetimeEpoch": 1680408000,
            "description": "Cloudy skies throughout the day.",
            "dew": 8.7,
            "feelslike": 10.8,
            "feelslikemax": 16.5,
            "feelslikemin": 6.1,
            "humidity": 83.4,
            "icon": "cloudy",
            "moonphase": 0.39,
            "precip": 9.4,
            "precipcover": 20.83,
            "precipprob": 42.9,
            "preciptype": [
                "rain"
            ],
            "pressure": 1015.9,
            "severerisk": 10.0,
            "snow": 0.0,
            "snowdepth": 0.0,
            "solarenergy": 4.3,
            "solarradiation": 50.0,
            "source": "fcst",
            "stations": null,
            "sunrise": "06:53:56",
            "sunriseEpoch": 1680432836,
            "sunset": "19:33:21",
            "sunsetEpoch": 1680478401,
            "temp": 11.6,
            "tempmax": 16.5,
            "tempmin": 8.5,
            "uvindex": 2.0,
            "visibility": 20.9,
            "winddir": 192.1,
            "windgust": 47.9,
            "windspeed": 14.8
        },
        {
            "cloudcover": 91.4,
            "conditions": "Overcast",
            "datetime": "2023-04-03",
            "datetimeEpoch": 1680494400,
            "description": "Cloudy skies throughout the day.",
            "dew": 5.4,
            "feelslike": 16.3,
            "feelslikemax": 23.3,
            "feelslikemin": 10.4,
            "humidity": 52.2,
            "icon": "cloudy",
            "moonphase": 0.42,
            "precip": 0.0,
            "precipcover": 0.0,
            "precipprob": 28.6,
            "preciptype": [
                "rain"
            ],
            "pressure": 1010.0,
            "severerisk": 10.0,
            "snow": 0.0,
            "snowdepth": 0.0,
            "solarenergy": 22.5,
            "solarradiation": 259.4,
            "source": "fcst",
            "stations": null,
            "sunrise": "06:52:27",
            "sunriseEpoch": 1680519147,
            "sunset": "19:34:15",
            "sunsetEpoch": 1680564855,
            "temp": 16.3,
            "tempmax": 23.3,
            "tempmin": 10.4,
            "uvindex": 8.0,
            "visibility": 24.0,
            "winddir": 269.2,
            "windgust": 61.9,
            "windspeed": 24.1
        },
        {
            "cloudcover": 30.5,
            "conditions": "Partially cloudy",
            "datetime": "2023-04-04",
            "datetimeEpoch": 1680580800,
            "description": "Becoming cloudy in the afternoon.",
            "dew": -4.5,
            "feelslike": 6.9,
            "feelslikemax": 12.1,
            "feelslikemin": 1.9,
            "humidity": 40.2,
            "icon": "partly-cloudy-day",
            "moonphase": 0.45,
            "precip": 0.0,
            "precipcover": 0.0,
            "precipprob": 19.0,
            "preciptype": null,
            "pressure": 1013.6,
            "severerisk": 10.0,
            "snow": 0.0,
            "snowdepth": 0.0,
            "solarenergy": 25.5,
            "solarradiation": 292.6,
            "source": "fcst",
            "stations": null,
            "sunrise": "06:50:58",
            "sunriseEpoch": 1680605458,
            "sunset": "19:35:10",
            "sunsetEpoch": 1680651310,
            "temp": 8.8,
            "tempmax": 12.1,
            "tempmin": 5.2,
            "uvindex": 9.0,
            "visibility": 24.1,
            "winddir": 311.3,
            "windgust": 46.8,
            "windspeed": 23.8
        },
        {
            "cloudcover": 0.0,
            "conditions": "Clear",
            "datetime": "2023-04-05",
            "datetimeEpoch": 1680667200,
            "description": "Clear conditions throughout the day.",
            "dew": -10.2,
            "feelslike": 4.7,
            "feelslikemax": 13.3,
            "feelslikemin": -2.0,
            "humidity": 29.3,
            "icon": "clear-day",
            "moonphase": 0.48,
            "precip": 0.0,
            "precipcover": 0.0,
            "precipprob": 19.0,
            "preciptype": null,
            "pressure": 1020.9,
            "severerisk": 10.0,
            "snow": 0.0,
            "snowdepth": 0.0,
            "solarenergy": 26.1,
            "solarradiation": 302.1,
            "source": "fcst",
            "stations": null,
            "sunrise": "06:49:29",
            "sunriseEpoch": 1680691769,
            "sunset": "19:36:04",
            "sunsetEpoch": 1680737764,
            "temp": 7.2,
            "tempmax": 13.3,
            "tempmin": 2.0,
            "uvindex": 9.0,
            "visibility": 24.1,
            "winddir": 317.9,
            "windgust": 48.2,
            "windspeed": 24.1
        }
    ],
    "latitude": 37.5407,
    "longitude": -77.4337,
    "queryCost": 1,
    "resolvedAddress": "Richmond, VA, United States",
    "stations": {
        "1269W": {
            "contribution": 0.0,
            "distance": 68455.0,
            "id": "1269W",
            "latitude": 37.088,
            "longitude": -77.957,
            "name": "Southern Piedmont VA US WEATHERSTEM",
            "quality": 0,
            "useCount": 0
        },
        "F2053": {
            "contribution": 0.0,
            "distance": 3204.0,
            "id": "F2053",
            "latitude": 37.554,
            "longitude": -77.466,
            "name": "FW2053 Richmond VA US",
            "quality": 0,
            "useCount": 0
        },
        "KFCI": {
            "contribution": 0.0,
            "distance": 16426.0,
            "id": "KFCI",
            "latitude": 37.41,
            "longitude": -77.52,
            "name": "RICHMOND, VA",
            "quality": 89,
            "useCount": 0
        },
        "KOFP": {
            "contribution": 0.0,
            "distance": 17736.0,
            "id": "KOFP",
            "latitude": 37.7,
            "longitude": -77.43,
            "name": "KOFP",
            "quality": 100,
            "useCount": 0
        },
        "KRIC": {
            "contribution": 0.0,
            "distance": 10216.0,
            "id": "KRIC",
            "latitude": 37.5,
            "longitude": -77.33,
            "name": "RICHMOND/BYRD FI, VA",
            "quality": 100,
            "useCount": 0
        },
        "KW96": {
            "contribution": 0.0,
            "distance": 28937.0,
            "id": "KW96",
            "latitude": 37.5,
            "longitude": -77.11,
            "name": "KW96",
            "quality": 99,
            "useCount": 0
        }
    },
    "timezone": "America/New_York",
    "tzoffset": -4.0
}"""
