name: GWA build and test
on:   
  push:
    branches:
      - master
env:
  LINODE_ROOT_PASSWORD: ${{secrets.LINODE_ROOT_PASSWORD}}
  LINODE_CLI_TOKEN: ${{secrets.LINODE_CLI_TOKEN}} 
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  REPO_NAME: ${{secrets.REPO_NAME}}  
  DOCKER_IMAGE_NAME: cjtkirk1/gwa
  WEATHER_API_TOKEN: ${{secrets.WEATHER_API_TOKEN}}  

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code with a github Action
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - name: Basic build
        run: make build
      - name: Basic test
        run: make test
      - name: docker login
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
      - name: Push image to Dockerhub
        run: make _push
      - name: Final Status
        run: echo "This job's status is ${{ job.status }}."
  test-app:
    needs: build-app
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code with a github Action
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - name: Test the container from dockerhub
        run: ./test.sh
  deploy-app:
    needs: test-app
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code with a github Action
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - name: Create and test the deployment 
        run: make deploy_test





